#! /usr/bin/env bash

CMD=$(basename $0)
ARGS=""

# Find subcommands and subcommand arguments
SUB=$1; shift
for var in "$@"; do
	if [[ $var == \-* ]]
	then
		ARGS+="$var "
	else
		ARGS+="\"$var\" "
	fi
done

if [[ "${SUB}" ]]; then
	eval "~/.orgwide/${CMD}-cli/bin/${SUB} ${ARGS}"
else
	echo "No subcommand provided"
fi